language: scala

scala:
  2.11.11

jobs:
  include:
    stage: Compile and Test
    script: "sbt ++$TRAVIS_SCALA_VERSION coverage test"
    stage: Quality Gate
    script: "sbt ++$TRAVIS_SCALA_VERSION coverageReport"
